{% set name = "fast_hdbscan" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_hdbscan-{{ version }}.tar.gz
  sha256: 6c361f40de6dec92fcca60bcd1f94efe4a81524c95998d295cee98d7717ab0ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy >=1.21
    - numba >=0.56
    - scikit-learn >=1.1

test:
  imports:
    - fast_hdbscan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TutteInstitute/fast_hdbscan
  summary: A fast multicore version of hdbscan for low dimensional euclidean spaces
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
